schema_version = "1.0.0"
id = "sco_edgewise"
name = "SCO EdgeWise"
version = "2.0.6"
tagline = "Measure distances, edge lengths, and angles in Edit Mode"
maintainer = "BEAST_of_BURDEN <sun503@yahoo.com>"
type = "add-on"
website = "https://github.com/pwillard/sco_edgewise/discussions"

blender_version_min = "4.2.0"

# License information
license = [
  "SPDX:GPL-3.0-or-later",
]

# Tags (optional, but useful)
tags = ["Mesh", "Modeling"]
